apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: adbar
  labels:
    app: kafka
    app.kubernetes.io/part-of: adbar
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: kafka
    - port: 9093
      targetPort: 9093
      protocol: TCP
      name: kafka-internal
  selector:
    app: kafka
